### ISSUE TITLE
Make sure to mention that VETA doesn't run any tools

### ISSUE THREAD

**Issue by YStrauch** [PedroBarbosa/VETA#11]
This might be obvious to you, but I spent almost a full day to get my data into VETA just to find out that VETA doesn't actually run all those tools that are listed as supported.

I guess the paragraph "What VETA is not" tries to say this, but I sure didn't understand what it meant until too late. I would write "THIS DOESN'T RUN ANY OF THE TOOLS LISTED" in caps and blinking letters for fools like me.

**Comment by PedroBarbosa** [comment]
I will definitely emphasise that, thanks for the feedback.
